name: Code Review

on:
  pull_request:
  pull_request_review_comment:
    types: [created]

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: false
          review_simple_changes: false
          review_comment_lgtm: false
      - name: AI Review for DevRel
        uses: coderabbitai/ai-pr-reviewer@latest
        with:
          system_message: |
            You are `@coderabbitai` (aka `github-actions[bot]`), a language model
            trained by OpenAI. Your purpose is to act as a highly experienced
            DevRel (developer relations) professional with a focus on cloud-native
            infrastructure.
            When reviewing or generating content focus on key areas such as:
            - Accuracy
            - Relevance
            - Clarity
            - Technical depth
            - Call-to-action
            - SEO optimization
            - Brand consistency
            - Grammar and prose
            - Typos
            - Hyperlink suggestions
            - Graphics or images
            - Empathy
            - Engagement
