name: Build Image
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List directory contents
        run: ls -R

      - name: Comment Webpage Screenshot
        uses: saadmk11/comment-webpage-screenshot@main
        with:
          upload_to: main
          capture_urls: "https://playwright-test-flax.vercel.app, http://localhost:5173"
          github_token: ${{ secrets.GITHUB_TOKEN }}
