name: "Tests: E2E"

on: [pull_request]

env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}

jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: install playwright browsers
        run: pnpm exec playwright install --with-deps
      - name: pnpm run test:e2e
        run: pnpm test:e2e

  tests_e2e_netlify_prepare:
    name: Wait for deployment on Netlify
    runs-on: ubuntu-latest
    steps:
      - name: Waiting for Netlify Preview
        uses: josephduffy/wait-for-netlify-action@v1
        id: wait-for-netflify-preview
        with:
          site_name: "pull-request"
          max_timeout: 180

  tests_e2e_netlify:
    needs: tests_e2e_netlify_prepare
    name: Run end-to-end tests on Netlify PR preview
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: install playwright browsers
        run: pnpm exec playwright install --with-deps
      - name: pnpm run test:e2e
        run: pnpm test:e2e
        env:
          PLAYWRIGHT_TEST_BASE_URL: "https://deploy-preview-${{env.GITHUB_PR_NUMBER}}--pull-request.netlify.app/"
          DEBUG: pw:api
